// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9xKE67AjFSzuwGeWpdZXF4pAERmWswGc',
    appId: '1:675877122778:web:04f23c3d23f8e7c121abe3',
    messagingSenderId: '675877122778',
    projectId: 'menotes-test-flutter-sk',
    authDomain: 'menotes-test-flutter-sk.firebaseapp.com',
    storageBucket: 'menotes-test-flutter-sk.appspot.com',
    measurementId: 'G-V3MT9H3SS8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAit8b7CLbyExyc0AlGm2Hr1OOAeqduho4',
    appId: '1:675877122778:android:0ca5e5a5667b885c21abe3',
    messagingSenderId: '675877122778',
    projectId: 'menotes-test-flutter-sk',
    storageBucket: 'menotes-test-flutter-sk.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1vDrqICAE8e5IEG25h9ql1AMP6O4ibc0',
    appId: '1:675877122778:ios:6c787a59be38ad8421abe3',
    messagingSenderId: '675877122778',
    projectId: 'menotes-test-flutter-sk',
    storageBucket: 'menotes-test-flutter-sk.appspot.com',
    iosClientId: '675877122778-lig5nqi1o7cbe7nnjk5322eh3d190as7.apps.googleusercontent.com',
    iosBundleId: 'com.sergeyKlyuchnikov.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1vDrqICAE8e5IEG25h9ql1AMP6O4ibc0',
    appId: '1:675877122778:ios:6c787a59be38ad8421abe3',
    messagingSenderId: '675877122778',
    projectId: 'menotes-test-flutter-sk',
    storageBucket: 'menotes-test-flutter-sk.appspot.com',
    iosClientId: '675877122778-lig5nqi1o7cbe7nnjk5322eh3d190as7.apps.googleusercontent.com',
    iosBundleId: 'com.sergeyKlyuchnikov.mynotes',
  );
}
